### PR TITLE
Added settings parameters for gulp commands

### PR DESCRIPTION
**Pull request by kammala**
In our team we use `gulp dev` and `gulp prod` for our builds. I added 2 django settings parameters to customize these commands.

### CODE REVIEW

**Comment by nilliams** [comment]
Came here looking for this, looks like exactly what my team need to deal with our multiple deployment environments.

**Comment by beaugunderson** [comment]
cool, I'll merge this now; thanks @kammala!

**Comment by beaugunderson** [comment]
OK, this has been released as 2.1.1. Thanks again!

**Comment by nilliams** [comment]
Nice one, thanks!

**Pull request merged**
